version: 2
jobs:
  build:
    docker:
      - image: loadimpact/k6
    steps:
      - checkout
      - run: echo "A first hello"
      - run: echo "test"
      - run: echo "test1"
      - run: echo "TOMMM"
      - run: echo "test87787454"


test:
  override:
    - ~/loadimpact/k6 -q -o cloud loadtests/main.js
