version: 2
jobs:
  build:
    docker:
      - image: loadimpact/loadgentest-k6
    steps:
      - checkout
      - run: echo "A first hello"
      - run: echo "test"
      - run: echo "test1"
      - run: echo "TOMMM"
      - run: echo "test87787454"
      dependencies:
  cache_directories:
    - "~/k6-bin"

        post:
    - mkdir -p ~/k6-bin
    - |
      if [[ ! -f ~/k6-bin/k6 ]]; then
        mv loadimpact/loadgentest-k6 ~/k6-bin/k6;
      fi

test:
  override:
    - ~/k6-bin/k6 run -q -o cloud loadtests/main.js
