version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: echo "A first hello"
      test:
  override:
    - ~/k6-bin/k6 run -q -o cloud loadtests/main.js
