version: 2
jobs:
  lint:
    docker:
      - image: circleci/golang:1.12
    environment:
      GOPATH: /home/circleci/.go_workspace
    working_directory: /home/circleci/.go_workspace/src/github.com/loadimpact/k6
    steps:
      - checkout
      - run:
          name: Check dependencies
          command: |
            go version
            export PATH="$GOPATH/bin:$PATH"
            mkdir -p "$GOPATH/bin"
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep version
            dep status
            dep ensure -update -dry-run
      - run:
          name: Run linter
          command: |
            export PATH=$GOPATH/bin:$PATH
            go get -t ./...
            go get -u github.com/alecthomas/gometalinter
            gometalinter --install
            gometalinter --deadline 10m --config gometalinter.json --vendor ./...
test:
  override:
    - ~/k6-bin/k6 run -q -o cloud loadtests/main.js
