version: 2
jobs:
  build:
    docker:
      - image: loadimpact/loadgentest-k6
    steps:
      - checkout
      - run: echo "A first hello"
      - run: echo "test"
      - run: echo "test1"
      - run: echo "TOMMM"
      - run: echo "test87787454"
